-- MySQL Script generated by MySQL Workbench
-- 06/05/19 19:48:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema europaunhas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema europaunhas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `europaunhas` DEFAULT CHARACTER SET utf8 ;
USE `europaunhas` ;

-- -----------------------------------------------------
-- Table `europaunhas`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `europaunhas`.`menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `menu` VARCHAR(45) NOT NULL,
  `link` VARCHAR(45) NOT NULL,
  `icone` VARCHAR(45) NULL,
  `exibir` INT NOT NULL,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `europaunhas`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `europaunhas`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `europaunhas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `europaunhas`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `idperfil` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_perfil1_idx` (`idperfil` ASC),
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `europaunhas`.`perfil` (`idperfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `europaunhas`.`menu_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `europaunhas`.`menu_perfil` (
  `idmenu` INT NOT NULL,
  `idperfil` INT NOT NULL,
  PRIMARY KEY (`idmenu`, `idperfil`),
  INDEX `fk_menu_has_perfil_perfil1_idx` (`idperfil` ASC),
  INDEX `fk_menu_has_perfil_menu_idx` (`idmenu` ASC),
  CONSTRAINT `fk_menu_has_perfil_menu`
    FOREIGN KEY (`idmenu`)
    REFERENCES `europaunhas`.`menu` (`idmenu`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_menu_has_perfil_perfil1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `europaunhas`.`perfil` (`idperfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `europaunhas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `europaunhas`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `sexo` CHAR NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(13) NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `europaunhas`.`usuario` (`idusuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `europaunhas`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `europaunhas`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `sexo` CHAR NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(13) NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  INDEX `fk_funcionario_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `europaunhas`.`usuario` (`idusuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `europaunhas`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `europaunhas`.`servico` (
  `idservico` INT NOT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(150) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `preco` FLOAT NOT NULL,
  `link_img` VARCHAR(255) NOT NULL,
  `duracao` INT NOT NULL,
  PRIMARY KEY (`idservico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `europaunhas`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `europaunhas`.`agendamento` (
  `idagendamento` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `valor` FLOAT NOT NULL,
  `idfuncionario` INT NOT NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`idagendamento`),
  INDEX `fk_agendamento_funcionario1_idx` (`idfuncionario` ASC),
  INDEX `fk_agendamento_cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_agendamento_funcionario1`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `europaunhas`.`funcionario` (`idfuncionario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamento_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `europaunhas`.`cliente` (`idcliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `europaunhas`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `europaunhas`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `preco` FLOAT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `europaunhas`.`servico_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `europaunhas`.`servico_produto` (
  `idproduto` INT NOT NULL,
  `idservico` INT NOT NULL,
  `descontarqtd` INT NULL,
  PRIMARY KEY (`idproduto`, `idservico`),
  INDEX `fk_produto_has_servico_servico1_idx` (`idservico` ASC),
  INDEX `fk_produto_has_servico_produto1_idx` (`idproduto` ASC),
  CONSTRAINT `fk_produto_has_servico_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `europaunhas`.`produto` (`idproduto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produto_has_servico_servico1`
    FOREIGN KEY (`idservico`)
    REFERENCES `europaunhas`.`servico` (`idservico`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `europaunhas`.`agendamento_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `europaunhas`.`agendamento_servico` (
  `idagendamento` INT NOT NULL,
  `idservico` INT NOT NULL,
  `horario` VARCHAR(6) NOT NULL,
  `status` INT NOT NULL,

  PRIMARY KEY (`idagendamento`, `idservico`),
  INDEX `fk_agendamento_has_servico_servico1_idx` (`idservico` ASC),
  INDEX `fk_agendamento_has_servico_agendamento1_idx` (`idagendamento` ASC),
  CONSTRAINT `fk_agendamento_has_servico_agendamento1`
    FOREIGN KEY (`idagendamento`)
    REFERENCES `europaunhas`.`agendamento` (`idagendamento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamento_has_servico_servico1`
    FOREIGN KEY (`idservico`)
    REFERENCES `europaunhas`.`servico` (`idservico`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
